const PreSubmitValues = {
  nameOfInspector: "Name Of Inspector",
  nameOfSupervisor: "Name Of Supervisor",
  placeOfInspection: "Place Of Inspection",
  dateOfInspection: "Date Of Inspection",
  vehiclePlateNumber: "Vehicle Plate Number",
  inspectionPassed: "Inspection Passed",
  generalRemarks: "General Remarks",
  driversFirstName: "Driver's FirstName",
  driversMiddleName: "Driver's MiddleName",
  driversSurname: "Driver's SurName",
  driversMobile: "Driver's Mobile",
  driversEmail: "Driver's Email",
  driversLicenseNo: "Driver's License No",
  driversLicenseExpiryDate: "Driver's License Expiry Date",
  addressLine1: "AddressLine1",
  addressLine2: "AddressLine2",
  postalCode: "PostalCode",
  country: "Country",
  state: "State",
  city: "City",
  nameOfOwner: "Name Of Owner",
  ownersHouseAddress: "Owner's House Address",
  ownersMobileNo: "Owner's Mobile No",
  ownersNextOfKinName: "Owner's Next-Of-Kin Name",
  vehicleType: "Vehicle Type",
  vehicleMake: "Vehicle Make",
  vehicleModel: "Vehicle Model",
  yearOfManufacture: "Year Of Manufacture",
  ChassisNo: "Chassis No",
  EngineNo: "Engine No",
  MOTExpiry: "MOT Expiry",
  InsuranceExpiry: "Insurance Expiry",
  FuelGaugeWorking: "Fuel Gauge Working?",
  OilLevelPressureGaugeWorking: "Oil Level Pressure Gauge Working",
  TransmissionFluidLevel: "Transmission Fluid Level",
  PowerSteeringFluidLevel: "PowerSteering Fluid Level",
  BrakeFluidLevel: "Brake Fluid Level",
  BatteryCharge: "Battery Charge",
  WindshieldWiperFluid: "Windshield Wiper Fluid",
  RadiatorFluidLevel: "Radiator Fluid Level",
  FluidsLeakingUnderBus: "Fluids Leaking Under Bus?",
  EngineWarningLights: "Engine Warning Lights",
  OtherEngineFluidLevels: "Other Engine Fluid Levels",
  HeadlightsHiLow: "Headlights HiLow",
  FoglampsHazardlamps: "Foglamps/Hazardlamps",
  WindshieldCondition: "Windshield Condition",
  DirectionalSignalsFrontrear: "Directional Signals Front and Rear",
  TaillightsRunninglights: "Taillights/Runninglights",
  BrakelightsBackUpLights: "Brakelights/BackUpLights",
  TireconditionAirpressure: "Tirecondition Airpressure",
  LugnutsTight: "Lugnuts Tight?",
  WindowscanWindfreely: "Windows can Wind freely?",
  LuggageStoragedoorsEnginecompartmentPanels:
    "Luggage Storage doors Enginecompartment Panels",
  ExteriorClean: "Exterior Clean",
  BodyconditionScratchesDingsDents: "Body condition Scratches DingsDents",
  OtherExteriorChecks: "Other Exterior Checks",
  Mirrors: "Mirrors",
  WindshieldWipers: "Windshield Wipers",
  Horn: "Horn",
  ParkingBrake: "Parking Brake",
  Fans: "Fans",
  AirConditioning: "Air Conditioning",
  RadioEquipmentCellphone: "Radio Equipment Cellphone",
  CantheDoorsbeOpenedFreely: "Can the Doors be Opened Freely?",
  InteriorLights: "Interior Lights",
  DriverSeatBelts: "Driver SeatBelts",
  PassengerSeats: "Passenger Seats",
  FireExtinguisher: "Fire Extinguisher",
  OtherEmergencyGear: "Other Emergency Gear",
  DestinationSignbox: "Destination Signbox",
  WindowsCleanandcanWindFreely: "Windows Clean and can Wind Freely?",
  InteriorClean: "Interior Clean?",
  WastebinAvailableOrEmptied: "Wastebin Available Or Emptied?",
  OtherInteriorChecks: "Other Interior Checks",
  noOfDefectsOnBus: "No Of Defects On Bus",
  hasSupervisorBeenNotified: "Has Supervisor Been Notified?",
  images: "Verification Images"
};

export default PreSubmitValues;
